Repository Club-PARD/AESPArd_FE, pull requests merged in 2024-12, with the labels that each got.

#2 [Feat]: 녹화 후 비디오 플레이어 화면으로 이동
  AESPArd_FE/Controller/CameraViewController.swift
  AESPArd_FE/Controller/VideoPlayerController.swift
Labels: Feature

#4 [UI]: 탭바 디자인 추가
  AESPArd_FE.xcodeproj/project.pbxproj
  AESPArd_FE/Assets.xcassets/homeView/Contents.json
  AESPArd_FE/Assets.xcassets/homeView/LOGO.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/homeView/LOGO.imageset/LOGO (1).svg
  AESPArd_FE/Assets.xcassets/homeView/bookmark_O.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/homeView/bookmark_O.imageset/star-01 (2).svg
  AESPArd_FE/Assets.xcassets/homeView/bookmark_X.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/homeView/bookmark_X.imageset/star-01 (1).svg
  AESPArd_FE/Assets.xcassets/homeView/calendar-click.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/homeView/calendar-click.imageset/calendar.svg
  AESPArd_FE/Assets.xcassets/homeView/calendar.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/homeView/calendar.imageset/calendar (1).svg
  AESPArd_FE/Assets.xcassets/homeView/importanceStar-click.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/homeView/importanceStar-click.imageset/star-01 (3).svg
  AESPArd_FE/Assets.xcassets/homeView/importanceStar.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/homeView/importanceStar.imageset/star-01.svg
  AESPArd_FE/Assets.xcassets/homeView/searchIcon.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/homeView/searchIcon.imageset/Icon.svg
  AESPArd_FE/Assets.xcassets/homeView/trash-click.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/homeView/trash-click.imageset/trash-03 (1).svg
  AESPArd_FE/Assets.xcassets/homeView/trash.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/homeView/trash.imageset/trash-03.svg
  AESPArd_FE/Assets.xcassets/tapbar/Contents.json
  AESPArd_FE/Assets.xcassets/tapbar/Ellipse 1.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/tapbar/Ellipse 1.imageset/Ellipse 1 (1).svg
  AESPArd_FE/Assets.xcassets/tapbar/home-05 (1).imageset/Contents.json
  AESPArd_FE/Assets.xcassets/tapbar/home-05 (1).imageset/home-05 (1).svg
  AESPArd_FE/Assets.xcassets/tapbar/home-05.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/tapbar/home-05.imageset/home-05.svg
  AESPArd_FE/Assets.xcassets/tapbar/plus.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/tapbar/plus.imageset/plus (1).svg
  AESPArd_FE/Assets.xcassets/tapbar/user-02.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/tapbar/user-02.imageset/user-02.svg
  AESPArd_FE/Controller/CameraViewController.swift
  AESPArd_FE/Controller/HomeViewController.swift
  AESPArd_FE/Controller/MyViewController.swift
  AESPArd_FE/Controller/ViewController.swift
  AESPArd_FE/Fonts/Pretendard-Black.otf
  AESPArd_FE/Fonts/Pretendard-Bold.otf
  AESPArd_FE/Fonts/Pretendard-ExtraBold.otf
  AESPArd_FE/Fonts/Pretendard-ExtraLight.otf
  AESPArd_FE/Fonts/Pretendard-Light.otf
  AESPArd_FE/Fonts/Pretendard-Medium.otf
  AESPArd_FE/Fonts/Pretendard-Regular.otf
  AESPArd_FE/Fonts/Pretendard-SemiBold.otf
  AESPArd_FE/Fonts/Pretendard-Thin.otf
  AESPArd_FE/Info.plist
  AESPArd_FE/UIFont.swift
  AESPArd_FE/View/HomeTableView/HeaderTableCell.swift
  AESPArd_FE/View/HomeTableView/PTListFilterTableCell.swift
  AESPArd_FE/View/HomeTableView/PresentationListTableCell.swift
  AESPArd_FE/View/HomeTableView/ScoreGraphTableCell.swift
Labels: Style

#5 [UI] 홈 화면 UI 완료
  AESPArd_FE/Assets.xcassets/homeView/check_O.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/homeView/check_O.imageset/Frame 2087327106.svg
  AESPArd_FE/Assets.xcassets/homeView/check_X.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/homeView/check_X.imageset/Frame 2087327106 (1).svg
  AESPArd_FE/Controller/HomeViewController.swift
  AESPArd_FE/Controller/ViewController.swift
  AESPArd_FE/View/HomeTableView/BarGraphView.swift
  AESPArd_FE/View/HomeTableView/CircularProgressBar.swift
  AESPArd_FE/View/HomeTableView/PresentationListTableCell.swift
  AESPArd_FE/View/HomeTableView/ScoreGraphTableCell.swift
Labels: Style

#6 [UI]: 선그래프 제외 ListUI 일단 완료
  AESPArd_FE/Assets.xcassets/listView/Contents.json
  AESPArd_FE/Assets.xcassets/listView/back.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/listView/back.imageset/chevron-left.svg
  AESPArd_FE/Assets.xcassets/listView/check_O.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/listView/check_O.imageset/Frame 2087327106 (2).svg
  AESPArd_FE/Assets.xcassets/listView/check_X.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/listView/check_X.imageset/Frame 2087327106 (3).svg
  AESPArd_FE/Assets.xcassets/listView/more.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/listView/more.imageset/dots-vertical.svg
  AESPArd_FE/Assets.xcassets/listView/talk.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/listView/talk.imageset/Union (1).svg
  AESPArd_FE/Assets.xcassets/listView/trash_O.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/listView/trash_O.imageset/trash-03 (3).svg
  AESPArd_FE/Assets.xcassets/listView/trash_X.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/listView/trash_X.imageset/trash-03 (2).svg
  AESPArd_FE/Controller/CameraViewController.swift
  AESPArd_FE/Controller/HomeViewController.swift
  AESPArd_FE/Controller/ListViewController.swift
  AESPArd_FE/Controller/ViewController.swift
  AESPArd_FE/View/HomeTableView/PTListFilterTableCell.swift
  AESPArd_FE/View/HomeTableView/PresentationListTableCell.swift
  AESPArd_FE/View/ListTableView/DeleteSelectedListTableCell.swift
  AESPArd_FE/View/ListTableView/EditPresentationView.swift
  AESPArd_FE/View/ListTableView/LineGraphTableCell.swift
  AESPArd_FE/View/ListTableView/ListHeaderTableCell.swift
  AESPArd_FE/View/ListTableView/PracticeListTableCell.swift
  AESPArd_FE/View/ListTableView/SmallCircularProgressBar.swift
Labels: Style

#8 [Merge] : 1번 모달과 2번 모달 구현 및 ListPage 병합 완료
  AESPArd_FE.xcodeproj/project.pbxproj
  AESPArd_FE/Assets.xcassets/AddModalView/Contents.json
  AESPArd_FE/Assets.xcassets/AddModalView/Plus-iCon.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/AddModalView/Plus-iCon.imageset/Icon-2.svg
  AESPArd_FE/Assets.xcassets/AddModalView/TimeSet.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/AddModalView/TimeSet.imageset/Icon-3.svg
  AESPArd_FE/Assets.xcassets/AddModalView/X-iCon.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/AddModalView/X-iCon.imageset/Icon.svg
  AESPArd_FE/Assets.xcassets/NewExtraModalView/Contents.json
  AESPArd_FE/Assets.xcassets/NewExtraModalView/Time.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/NewExtraModalView/Time.imageset/Icon-3.svg
  AESPArd_FE/Controller/AddModalViewController.swift
  AESPArd_FE/Controller/HomeViewController.swift
  AESPArd_FE/Controller/NewExtraModalViewController.swift
  AESPArd_FE/Controller/ViewController.swift
  AESPArd_FE/Info.plist
  AESPArd_FE/View/ModalView/AddModalTableViewCell.swift
  AESPArd_FE/View/ModalView/FirstTimeSettingButtonView.swift
  AESPArd_FE/View/ModalView/NewExtraModalView.swift
  AESPArd_FE/View/ModalView/SecondTimeSettingButtonView.swift
Labels: Style

#9 [UI] : MyPage 구현
  AESPArd_FE.xcodeproj/project.pbxproj
  AESPArd_FE/Assets.xcassets/MyView/Contents.json
  AESPArd_FE/Assets.xcassets/MyView/logout.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/MyView/logout.imageset/log-out-02.svg
  AESPArd_FE/Assets.xcassets/MyView/phone.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/MyView/phone.imageset/phone.svg
  AESPArd_FE/Assets.xcassets/MyView/reset.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/MyView/reset.imageset/refresh-ccw-01.svg
  AESPArd_FE/Controller/MyViewController.swift
  AESPArd_FE/View/ModalView/NewExtraModalView.swift
Labels: Style

#10 [UI]: 비디오플레이어 제외 resultUI 완료
  .gitignore
  AESPArd_FE.xcodeproj/project.pbxproj
  AESPArd_FE/Assets.xcassets/listView/check_O.imageset/Frame 2087327106 (2).svg
  AESPArd_FE/Assets.xcassets/listView/check_X.imageset/Frame 2087327106 (3).svg
  AESPArd_FE/Assets.xcassets/resultView/chevron-left (1).imageset/Contents.json
  AESPArd_FE/Assets.xcassets/resultView/chevron-left (1).imageset/chevron-left (1).svg
  AESPArd_FE/Assets.xcassets/tapbar/home.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/tapbar/home.imageset/home-05 (1).svg
  AESPArd_FE/Assets.xcassets/tapbar/user-02.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/tapbar/user-02.imageset/user-02 (1).svg
  AESPArd_FE/Assets.xcassets/tapbar/user-02.imageset/user-02.svg
  AESPArd_FE/Assets.xcassets/tapbar/user.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/tapbar/user.imageset/user-02 (2).svg
  AESPArd_FE/Controller/ResultReportViewController.swift
  AESPArd_FE/Controller/ViewController.swift
  AESPArd_FE/Network/APIService.swift
  AESPArd_FE/Network/NetworkManager.swift
  AESPArd_FE/View/ResultTableView/DropDownDetailTableCell.swift
  AESPArd_FE/View/ResultTableView/GoToEvaluationCell.swift
Labels: Style

#11 [UI] : 마이페이지 UI 알람창, 토스트메세지 구현 완료
  AESPArd_FE/Controller/AddModalViewController.swift
  AESPArd_FE/Controller/MyViewController.swift
  AESPArd_FE/Controller/NewExtraModalViewController.swift
  AESPArd_FE/View/ModalView/AddModalTableViewCell.swift
  AESPArd_FE/View/ModalView/FirstTimeSettingButtonView.swift
  AESPArd_FE/View/ModalView/SecondTimeSettingButtonView.swift
  AESPArd_FE/View/MyView/ButtonContainer.swift
Labels: Style

#12 [영상촬영과 시선 추적 통합] : 영상촬영과 시선 추적을 통합하고 녹화 종료 후 다음 화면으로 넘어가도록 하였음
  AESPArd_FE.xcodeproj/project.pbxproj
  AESPArd_FE/Assets.xcassets/CameraView/Contents.json
  AESPArd_FE/Assets.xcassets/CameraView/Cursor.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/CameraView/Cursor.imageset/Cursor.png
  AESPArd_FE/Controller/CameraViewController.swift
  AESPArd_FE/Controller/Recording/ AnalyzingViewController.swift
  AESPArd_FE/Controller/Recording/CameraOverlayViewController.swift
  AESPArd_FE/Controller/Recording/CameraViewController.swift
  AESPArd_FE/Controller/ViewController.swift
  AESPArd_FE/Extensions/EyeTracking/SCNHitTestResult.swift
  AESPArd_FE/Extensions/Notifications.swift
  AESPArd_FE/SceneDelegate.swift
  AESPArd_FE/View/EyeTrackingView/EyeNode.swift
  AESPArd_FE/View/RecordingView/CameraOverlayView.swift
  AESPArd_FE/ko.lproj/LaunchScreen.strings
Labels: Feature

#14 [Fix]: 테이블뷰 셀 reuse 오류 해결
  AESPArd_FE/Controller/HomeViewController.swift
  AESPArd_FE/Controller/ListViewController.swift
  AESPArd_FE/Controller/SearchViewController.swift
  AESPArd_FE/View/HomeTableView/BarGraphView.swift
  AESPArd_FE/View/HomeTableView/PTListFilterTableCell.swift
  AESPArd_FE/View/HomeTableView/PresentationListTableCell.swift
  AESPArd_FE/View/ListTableView/PracticeListTableCell.swift
Labels: Bug

#15 [UI] : 평가기준표 모달 구현 중
  AESPArd_FE.xcodeproj/project.pbxproj
  AESPArd_FE/Controller/AddModalViewController.swift
  AESPArd_FE/Controller/NewExtraModalViewController.swift
  AESPArd_FE/Network/APIService.swift
  AESPArd_FE/Network/NetworkManager.swift
  AESPArd_FE/View/ResultTableView/EvaluationModalView.swift
  AESPArd_FE/View/ResultTableView/GoToEvaluationCell.swift
Labels: Style

#16 [클백연결 기초 세팅] : Moya 라이브러리 설치 후 기본 세팅 완료
  AESPArd_FE.xcodeproj/project.pbxproj
  AESPArd_FE.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  AESPArd_FE/Controller/HomeViewController.swift
  AESPArd_FE/Info.plist
  AESPArd_FE/Model/User.swift
  AESPArd_FE/Network/API/AuthService.swift
  AESPArd_FE/Network/API/UserService.swift
  AESPArd_FE/Network/APIService.swift
  AESPArd_FE/Network/NetworkManager.swift
  AESPArd_FE/Network/Provider/NetworkManager.swift
Labels: API

#17 [UI] : 평가기준표 모달 페이지 구현
  .gitignore
  AESPArd_FE/Network/URLClass.swift
  AESPArd_FE/View/ResultTableView/EvaluationModalView.swift
  AESPArd_FE/View/ResultTableView/InfoView.swift
Labels: Style

#19 [UI] : 스플래시 비디오 추가 및 apple로그인 버튼 추가
  AESPArd_FE.xcodeproj/project.pbxproj
  AESPArd_FE/Assets.xcassets/Splash/Contents.json
  AESPArd_FE/Assets.xcassets/Splash/SplashView(Pree.mp4).dataset/Contents.json
  AESPArd_FE/Assets.xcassets/Splash/SplashView(Pree.mp4).dataset/SplashView(Pree.mp4).mp4
  AESPArd_FE/Controller/SplashViewController.swift
  AESPArd_FE/SceneDelegate.swift
  AESPArd_FE/Video/SplashVideo.mp4
  AESPArd_FE/View/ResultTableView/EvaluationModalView.swift
Labels: Style

#20 [오디오 보내기 위한 로직 1차 및 예외처리 및 UI수정] : 제목이 곧 내용
  AESPArd_FE/Controller/AddModalViewController.swift
  AESPArd_FE/Controller/NewExtraModalViewController.swift
  AESPArd_FE/Controller/Recording/ AnalyzingViewController.swift
  AESPArd_FE/Controller/Recording/CameraOverlayViewController.swift
  AESPArd_FE/Controller/Recording/CameraViewController.swift
  AESPArd_FE/Controller/ViewController.swift
  AESPArd_FE/Extensions/Notifications.swift
  AESPArd_FE/Model/NewPresentation.swift
  AESPArd_FE/Model/UploadAudioResponse.swift
  AESPArd_FE/Network/API/PresentationService.swift
  AESPArd_FE/Network/Provider/NetworkManager.swift
  AESPArd_FE/Network/URLClass.swift
  AESPArd_FE/View/ModalView/FirstTimeSettingButtonView.swift
  AESPArd_FE/View/ModalView/SecondTimeSettingButtonView.swift
  AESPArd_FE/View/RecordingView/CameraOverlayView.swift
Labels: Bug, Feature

#21 [API]: 홈 화면 클백 완료
  AESPArd_FE.xcodeproj/project.pbxproj
  AESPArd_FE/Assets.xcassets/searchView/Contents.json
  AESPArd_FE/Assets.xcassets/searchView/x-close.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/searchView/x-close.imageset/x-close.svg
  AESPArd_FE/Controller/HomeViewController.swift
  AESPArd_FE/Controller/ResultReportViewController.swift
  AESPArd_FE/Controller/SearchViewController.swift
  AESPArd_FE/Controller/ViewController.swift
  AESPArd_FE/Model/PresentationList.swift
  AESPArd_FE/Model/User.swift
  AESPArd_FE/Network/API/PresentationsService.swift
  AESPArd_FE/Network/API/RecordService.swift
  AESPArd_FE/Network/API/UserService.swift
  AESPArd_FE/Network/Provider/NetworkManager.swift
  AESPArd_FE/View/HomeTableView/HeaderLogoView.swift
  AESPArd_FE/View/HomeTableView/PTListFilterTableCell.swift
  AESPArd_FE/View/HomeTableView/PresentationListTableCell.swift
  AESPArd_FE/View/ResultTableView/PracticeTotalScoreView.swift
Labels: API

#22 [UI] : 애플로그인 및 모달뷰 오류 수정
  .gitignore
  AESPArd_FE.xcodeproj/project.pbxproj
  AESPArd_FE/AESPArd_FE.entitlements
  AESPArd_FE/Assets.xcassets/Splash/Contents.json
  AESPArd_FE/Assets.xcassets/Splash/SplashView(Pree.mp4).dataset/Contents.json
  AESPArd_FE/Assets.xcassets/Splash/SplashView(Pree.mp4).dataset/SplashView(Pree.mp4).mp4
  AESPArd_FE/Controller/NewExtraModalViewController.swift
  AESPArd_FE/Controller/SplashViewController.swift
  AESPArd_FE/Model/UserInfo.swift
  AESPArd_FE/View/ModalView/FirstTimeSettingButtonView.swift
  AESPArd_FE/View/ModalView/SecondTimeSettingButtonView.swift
Labels: Style, Bug

#23 [API]: Search & my 페이지 클백 연결 완
  AESPArd_FE.xcodeproj/project.pbxproj
  AESPArd_FE/Controller/HomeViewController.swift
  AESPArd_FE/Controller/MyViewController.swift
  AESPArd_FE/Controller/SearchViewController.swift
  AESPArd_FE/Model/User.swift
  AESPArd_FE/Network/API/PresentationsService.swift
  AESPArd_FE/Network/API/UserService.swift
  AESPArd_FE/Network/Provider/NetworkManager.swift
  AESPArd_FE/Network/URLClass.swift
Labels: API

#25 [UI] : NewExtraModal창 시간 오류 라벨 추가
  AESPArd_FE/Assets.xcassets/NewExtraModalView/sipja.imageset/Contents.json
  AESPArd_FE/Assets.xcassets/NewExtraModalView/sipja.imageset/plus.svg
  AESPArd_FE/Controller/AddModalViewController.swift
  AESPArd_FE/Controller/NewExtraModalViewController.swift
  AESPArd_FE/View/ModalView/FirstTimeSettingButtonView.swift
  AESPArd_FE/View/ModalView/SecondTimeSettingButtonView.swift
Labels: Style, Feature

#26 [모달창 발표리스트 불러오기] : 모달창 발표리스트 불러오기 클백 연결 성공
  AESPArd_FE.xcodeproj/xcuserdata/dogyung.xcuserdatad/xcschemes/xcschememanagement.plist
  AESPArd_FE/Controller/AddModalViewController.swift
  AESPArd_FE/Model/NewPractice.swift
  AESPArd_FE/Model/PresentationForModal.swift
  AESPArd_FE/Network/API/NewPresentationAndNewPracticeService.swift
  AESPArd_FE/Network/API/PresentationsService.swift
  AESPArd_FE/Network/Provider/NetworkManager.swift
  AESPArd_FE/View/ModalView/AddModalTableViewCell.swift
Labels: API

#27 [API] List 페이지 get API 완료
  AESPArd_FE/Controller/HomeViewController.swift
  AESPArd_FE/Controller/ListViewController.swift
  AESPArd_FE/Controller/ResultReportViewController.swift
  AESPArd_FE/Controller/SearchViewController.swift
  AESPArd_FE/Model/GetPractice.swift
  AESPArd_FE/Network/API/PracticeService.swift
  AESPArd_FE/Network/Provider/NetworkManager.swift
  AESPArd_FE/View/ListTableView/LineChartCustomView.swift
  AESPArd_FE/View/ListTableView/LineGraphTableCell.swift
  AESPArd_FE/View/ListTableView/ListHeaderView.swift
  AESPArd_FE/View/ListTableView/PracticeListTableCell.swift
  AESPArd_FE/View/ResultTableView/PracticeHeaderView.swift
Labels: API

#28 [Bug] : 모달창 사라지는 버그 해결
  AESPArd_FE/Controller/MyViewController.swift
  AESPArd_FE/Controller/NewExtraModalViewController.swift
  AESPArd_FE/View/HomeTableView/PTListFilterTableCell.swift
  AESPArd_FE/View/HomeTableView/ScoreGraphTableCell.swift
Labels: Bug

#29 [Chore]: 검색바 및 워딩 디테일 수정
  AESPArd_FE/Controller/HomeViewController.swift
  AESPArd_FE/Controller/SearchViewController.swift
  AESPArd_FE/View/HomeTableView/PTListFilterTableCell.swift
Labels: Style

#31 [서버에 발표&연습 전달 성공] : 기존 발표에서 새로운 연습 & 새로운 발표와 그 연습 생성 성공
  AESPArd_FE/Controller/NewExtraModalViewController.swift
  AESPArd_FE/Controller/Recording/ AnalyzingViewController.swift
  AESPArd_FE/Controller/Recording/CameraViewController.swift
  AESPArd_FE/Model/NewPractice.swift
  AESPArd_FE/Model/NewPresentation.swift
  AESPArd_FE/Network/API/NewPresentationAndNewPracticeService.swift
  AESPArd_FE/Network/Provider/NetworkManager.swift
Labels: API

#33 [Bug] : searchBar, 평가기준표 모달창 버그 수정
  AESPArd_FE/Assets.xcassets/AppIcon.appiconset/Contents.json
  AESPArd_FE/Assets.xcassets/AppIcon.appiconset/pree(App-icon).png
  AESPArd_FE/Controller/NewExtraModalViewController.swift
  AESPArd_FE/Controller/SearchViewController.swift
  AESPArd_FE/View/ResultTableView/EvaluationModalView.swift
Labels: Style, Bug

#35 [오류들 수정]: 여러가지 오류들 수정
  AESPArd_FE/AppDelegate.swift
  AESPArd_FE/Controller/AddModalViewController.swift
  AESPArd_FE/Controller/Recording/ AnalyzingViewController.swift
  AESPArd_FE/Controller/Recording/CameraViewController.swift
Labels: Bug

#36 [API]: result 페이지 API get 완료
  AESPArd_FE/Controller/ListViewController.swift
  AESPArd_FE/Controller/ResultReportViewController.swift
  AESPArd_FE/Model/GetPractice.swift
  AESPArd_FE/Model/GetReport.swift
  AESPArd_FE/Network/API/ReportsService.swift
  AESPArd_FE/Network/Provider/NetworkManager.swift
  AESPArd_FE/View/ResultTableView/PracticeTotalScoreView.swift
Labels: API

#38 [Feat]: PHAsset으로 비디오 플레이어 실행하기 추가
  AESPArd_FE/Controller/ResultReportViewController.swift
  AESPArd_FE/View/ResultTableView/VideoPlayerView.swift
Labels: Feature

#40 [Bug] : AddModalView에서 셀을 선택했을 때 다중선택버그 수정
  AESPArd_FE/Controller/AddModalViewController.swift
  AESPArd_FE/Network/API/AuthService.swift
  AESPArd_FE/View/ModalView/AddModalTableViewCell.swift
Labels: Bug
