Repository Club-PARD/AESPArd_FE, pull requests merged in 2025-01, with the labels that each got.

#41 [Fix]: 탭바 클릭시 비디오 플레이어 실행 오류 notificationCenter로 해결
  AESPArd_FE/Controller/HomeViewController.swift
  AESPArd_FE/Controller/MyViewController.swift
  AESPArd_FE/Controller/ResultReportViewController.swift
  AESPArd_FE/Controller/SearchViewController.swift
  AESPArd_FE/Controller/VideoPlayerController.swift
  AESPArd_FE/Controller/ViewController.swift
  AESPArd_FE/Network/API/PresentationsService.swift
  AESPArd_FE/Network/Provider/NetworkManager.swift
Labels: Bug

#42 [로딩창 To 리포트 ]: 영상 보내고 로딩창에서 분석 결과 기다렸다가 리포트 뷰컨으로 넘어가는 것 구현
  AESPArd_FE.xcodeproj/project.pbxproj
  AESPArd_FE/Controller/Recording/ AnalyzingViewController.swift
  AESPArd_FE/Controller/Recording/CameraViewController.swift
  AESPArd_FE/Controller/ResultReportViewController.swift
  AESPArd_FE/Info.plist
  AESPArd_FE/Model/NewPresentation.swift
  AESPArd_FE/Network/API/PracticeService.swift
  AESPArd_FE/Network/Provider/NetworkManager.swift
Labels: API, Feature

#43 [API] : 애플 로그인 NetworkManager 구현
  AESPArd_FE/Network/Provider/NetworkManager.swift
Labels: API

#45 [API]: list, report 페이지 delete/patch 연결 완료
  AESPArd_FE/Controller/HomeViewController.swift
  AESPArd_FE/Controller/ListViewController.swift
  AESPArd_FE/Controller/ResultReportViewController.swift
  AESPArd_FE/Network/API/PracticeService.swift
  AESPArd_FE/Network/API/PresentationsService.swift
  AESPArd_FE/Network/Provider/NetworkManager.swift
  AESPArd_FE/View/ListTableView/DeleteSelectedListTableCell.swift
  AESPArd_FE/View/ListTableView/LineChartCustomView.swift
  AESPArd_FE/View/ResultTableView/EditPracticeView.swift
Labels: API

#46 [Fix]: list 페이지 연습 선택 삭제 렌더링 문제 해결
  AESPArd_FE/Controller/ListViewController.swift
Labels: Bug

#49 [Refacgtor] : 제한시간 20분 되면 촬영 종료되도록 코드 수정
  AESPArd_FE.xcodeproj/project.pbxproj
  AESPArd_FE.xcodeproj/xcshareddata/xcschemes/AESPArd_FE.xcscheme
  AESPArd_FE.xcodeproj/xcuserdata/dogyung.xcuserdatad/xcschemes/xcschememanagement.plist
  AESPArd_FE/Controller/Recording/CameraViewController.swift
Labels: Refactor
